apiVersion: v1
kind: Pod
metadata:
  name: drop-good01
spec:
  initContainers:
  - name: init
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["CAP_NET_RAW"]
  containers:
  - name: add-capabilities
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["CAP_NET_RAW"]
---
apiVersion: v1
kind: Pod
metadata:
  name: drop-good02
spec:
  initContainers:
  - name: init
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["ALL"]
  containers:
  - name: add-capabilities
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["ALL"]
---
apiVersion: v1
kind: Pod
metadata:
  name: drop-good03
spec:
  initContainers:
  - name: init
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["ALL", "CAP_NET_RAW"]
  containers:
  - name: add-capabilities
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["ALL", "CAP_NET_RAW"]
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod01
spec:
  initContainers:
  - name: init
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["CAP_NET_RAW"]
  containers:
  - name: add-capabilities
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["CAP_CHOWN"]
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod02
spec:
  containers:
  - name: add-capabilities
    image: gcr.io/google-samples/node-hello:1.0
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod03
spec:
  initContainers:
  - name: init
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["CAP_NET_RAW"]
        add: ["CAP_NET_RAW"]
  containers:
  - name: add-capabilities
    image: gcr.io/google-samples/node-hello:1.0
    securityContext:
      capabilities:
        drop: ["CAP_CHOWN"]
        add: ["CAP_NET_RAW"]
